name: Build and Deploy to EC2 via Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ GitHub 리포지토리 체크아웃
      - name: Checkout Repository
        uses: actions/checkout@v2

      # 2️⃣ JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3️⃣ 빌드 실행 (Docker DB 사용)
      - name: Build with Gradle
        run: |
          docker-compose up -d
          ./gradlew clean build
          docker-compose down

      # 4️⃣ Docker Hub 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      # 5️⃣ Docker 이미지 빌드 및 Docker Hub에 푸시
      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/wedvice-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/wedvice-app:latest

      # 6️⃣ EC2에서 Docker 이미지 Pull 및 실행 (RDS 연결)
      - name: SSH to EC2 and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop wedvice-app || true
            docker rm wedvice-app || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/wedvice-app:latest
            docker run -d -p 8080:8080 \
              -e SPRING_DATASOURCE_URL=jdbc:postgresql://${{ secrets.RDS_ENDPOINT }}:5432/wedvice-db \
              -e SPRING_DATASOURCE_USERNAME=wedviceuser \
              -e SPRING_DATASOURCE_PASSWORD=wedvicepass \
              ${{ secrets.DOCKER_USERNAME }}/wedvice-app:latest
